name 'google-chrome'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures google-chrome'
long_description 'Installs/Configures google-chrome'
version '0.1.0'
