name 		'scripts'
maintainer 	'Greg K'
maintainer_email 'grifkon@gmail.com'
license 	'all_rights'
description 	'Installs/Configures scripts'
long_description 'Installs/Configures scripts'
depends		'apt'
version 	'0.1.0'
