name 'scripts'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures scripts'
long_description 'Installs/Configures scripts'
version '0.1.0'
